spring.application.name=prompthub
spring.thymeleaf.cache=false
spring.datasource.url=jdbc:postgresql://localhost:5432/prompthub
spring.datasource.username=postgres
spring.datasource.password=Pvs182614Va
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
